steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-00-f7a6f7118add/dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s

options:
  pool:
    name: 'projects/qwiklabs-gcp-00-f7a6f7118add/locations/us-central1/workerPools/4'
